Add general user settings and user registration settings
evoto-tech/EvotoApi pull request #52
Opened 2017-04-08 11:30 UTC by maael

2017-04-08 14:53 UTC, MetalMichael requested changes

2017-04-08 14:53 UTC, MetalMichael commented on EvotoApi/Areas/Management/Connections/RegistrarConnection.cs
> +            var exception = new Exception("Error listing registrar settings");
I feel like this should be a custom exception if you want to add metadata. Is the metadata needed or just for debugging purposes?

2017-04-08 14:53 UTC, MetalMichael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +                ModelState.AddModelError("error", e);
should be e.Message? Regardless, shouldn't be revealing internal errors, and should probably just return internalservererror

2017-04-08 14:53 UTC, MetalMichael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +        //[Authorize]
tag as todo

2017-04-08 14:53 UTC, MetalMichael commented on Registrar.Database/Interfaces/IRegiSettingStore.cs
> +        Task<SingleRegiSettingResponse> UpdateSetting(UpdateRegiSetting settingName);
Why is the database returning response models?

2017-04-08 14:53 UTC, MetalMichael commented on Registrar.Database/Migrations/M014CreateSettingsTableWithRegistrationDefault.cs
> +                .WithColumn("Id").AsInt32().Identity().NotNullable()
Is ID needed?

2017-04-08 14:53 UTC, MetalMichael commented on Registrar.Models/Request/UpdateRegiSetting.cs
> +        [DataMember(Name="Value")]
capital?

2017-04-08 14:53 UTC, MetalMichael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +                return Json(settings);
Use `Ok(settings)` instead of Json

2017-04-08 14:53 UTC, MetalMichael commented on RegistrarApi/Controllers/SettingController.cs
> +                return Json(updatedSetting);
Use `Ok(updatedSetting)`

2017-04-08 14:53 UTC, MetalMichael commented on RegistrarApi/Controllers/SettingController.cs
> +                return NotFound();
Shouldn't this return an empty list?

2017-04-08 16:13 UTC, maael commented on RegistrarApi/Controllers/SettingController.cs
> +                return Json(updatedSetting);
If I use Ok I get xml. Any idea why? Json gives me a 200 anyway.

2017-04-08 16:13 UTC, maael commented on Registrar.Database/Migrations/M014CreateSettingsTableWithRegistrationDefault.cs
> +                .WithColumn("Id").AsInt32().Identity().NotNullable()
Name couldn't be the ID as identity can't be a string.

2017-04-08 16:13 UTC, maael commented on Registrar.Database/Interfaces/IRegiSettingStore.cs
> +        Task<SingleRegiSettingResponse> UpdateSetting(UpdateRegiSetting settingName);
So I don't have to have a pointless middleman model.

2017-04-08 16:14 UTC, maael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +                ModelState.AddModelError("error", e);
AddModelError takes an exception. But sure, I can get the internalservererror only thing.

2017-04-08 16:14 UTC, maael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +                return Json(settings);
If I use Ok I get xml. Any idea why? Json gives me a 200 anyway.

2017-04-08 16:15 UTC, maael commented on EvotoApi/Areas/Management/Connections/RegistrarConnection.cs
> +            var exception = new Exception("Error listing registrar settings");
Mainly for debugging I believe, and I just copied it from somewhere else you did it.

2017-04-08 16:16 UTC, MetalMichael commented on EvotoApi/Areas/Management/Controllers/RegistrarConnectionController.cs
> +                return Json(settings);
Ok() is dynamic and responds to the contentType of the request. Avoids unnecessary dependence on json

2017-04-08 16:16 UTC, maael commented on RegistrarApi/Controllers/SettingController.cs
> +                return NotFound();
Sure, we'd be masking the error but I guess it's not needed.

2017-04-08 16:19 UTC, MetalMichael commented on Registrar.Database/Interfaces/IRegiSettingStore.cs
> +        Task<SingleRegiSettingResponse> UpdateSetting(UpdateRegiSetting settingName);
It's not pointless. It's an application model, and can be adjusted to have specific methods or utilities to manipulate it throughout transient use. Response models dictate what is sent to the user/api. It doesn't make sense for a database to return a response model.

2017-04-08 16:21 UTC, MetalMichael commented on Registrar.Database/Migrations/M014CreateSettingsTableWithRegistrationDefault.cs
> +                .WithColumn("Id").AsInt32().Identity().NotNullable()
Identity just specifies that it should be a key and auto increment. Drop the whole line and the system works the same. You can even put the PrimaryKey() part inline, and use it like Identity()

2017-04-08 16:22 UTC, MetalMichael commented on EvotoApi/Areas/Management/Connections/RegistrarConnection.cs
> +            var exception = new Exception("Error listing registrar settings");
Unsure where, I don't recognize the exception.Data, didn't even know it existed. Normally I'd just throw a general exception, and if I needed to debug, break and analyse the response.

2017-04-08 16:24 UTC, MetalMichael commented on RegistrarApi/Controllers/SettingController.cs
> +                return NotFound();
Or just don't throw an exception in the Store, given that just because there are no settings, it doesn't necessarily indicate a problem

2017-04-09 08:04 UTC, maael commented on RegistrarApi/Controllers/SettingController.cs
> +                return NotFound();
But there is an error - if you're trying to get something and it isn't present you should get a Resource Not Found response, aka 404. 404's refer to any entity related to the request not being found, not just the route. If you then want to handle it not being found by showing an empty list, that's up to the client, not the server to decide. I'm leaving this as `NotFound`.

2017-04-09 12:06 UTC, MetalMichael commented on Registrar.Database/Migrations/M014CreateSettingsTableWithRegistrationDefault.cs
> +            Create.PrimaryKey("PK_Settings").OnTable("Settings")
Primary key declared twice?

2017-04-09 12:06 UTC, MetalMichael commented on RegistrarApi/Controllers/SettingController.cs
> +                return NotFound();
Should return empty list? Or return empty list in store and not throw exception. Listing all shouldn't return notfound ever really

2017-04-09 17:55 UTC, merged